Form section
dgcuenca/Portfolio pull request #3
Opened 2022-11-01 20:56 UTC by dgcuenca

In this pull request, I was able to:

  -  Create a form in the index.html using the pair programming method.

  -   Stylized this section in  HTML with CSS using flexbox the pair programming method.

2022-11-01 22:05 UTC, Lizdev-05 requested changes
Hi @dgcuenca, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![so-close](https://user-images.githubusercontent.com/73854999/199349491-6dd0c849-ab5b-4e94-8b5f-85353d5e48b7.gif)

## Highlights

- All linters checks are green ✔️
- Descriptive PR title and summary✔
- The repository is documented in a professional way 👍
- The form is submitted 💯

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
-styling your placeholder field

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 22:05 UTC, Lizdev-05 commented on index.html
> +						<li><a href="#"><img src="./icons/Twitterf.png" alt="twitter"></a></li>
Great job 👍 @dgcuenca , Kindly give your form page some padding to make your user interface meet the required [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471).
**Your design 👇**
![padding](https://user-images.githubusercontent.com/73854999/199350742-5a9fa898-1989-4168-90ea-7fbd864e5a59.jpg)

**Microverse design **
![pad](https://user-images.githubusercontent.com/73854999/199350806-66621736-0a9a-44fe-b02b-791b29e2e7b0.jpg)

2022-11-02 13:30 UTC, dgcuenca commented
In this pull request, I was able to:

-Give padding to the form.
-Style placeholders.

2022-11-02 13:34 UTC, omarsalem7 approved these changes
Hi @dgcuenca 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ No linter errors. 
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 14:31 UTC, merged